/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.wzf.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.aop.support.AopUtils;

import com.wzf.Dbconmb.DBUtil;
import com.wzf.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 10-13-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="type" validate="true"
 */
public class LoginAction extends DispatchAction {
	/*
	 * Generated Methods
	 */
	//如何捕捉异常 及  日志记录
	//如何  手动  反转注入  类，而不是从struts访问代理加载
	
//	private DBUtil dbutil;
//	
//	
//	public DBUtil getDbutil() {
//		return dbutil;
//	}
//
//
//	public void setDbutil(DBUtil dbutil) {
//		this.dbutil = dbutil;
//	}


	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward visit(ActionMapping mapping, ActionForm form,
			HttpServletRequest req, HttpServletResponse resp) {
		
		 DBUtil dbutil = new DBUtil();//如何通过构造函数注入，难道还级联？
		 System.out.println("aop:"+AopUtils.isAopProxy(dbutil));
		 System.out.println("cglib:"+AopUtils.isCglibProxy(dbutil));
		 System.out.println("jdk动态："+AopUtils.isJdkDynamicProxy(dbutil) );
		String phone=req.getParameter("phone");
		String name=req.getParameter("name");
		System.out.println("dbutil="+dbutil);
		if(dbutil!=null)
		if(phone!=null&&name!=null)
			dbutil.addUser(new User(phone,name,"0"));
		return mapping.findForward("success");
	}
}