/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.action;

import java.net.URLEncoder;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.chain.contexts.ActionContext;
import org.apache.struts.chain.contexts.ServletActionContext;
import org.springframework.aop.support.AopUtils;

import com.ssh.form.RegisterForm;
import com.ssh.model.User;
import com.ssh.pubvari.Variable;
import com.ssh.service.Inservice;
import com.ssh.service.Service;

/** 
 * MyEclipse Struts
 * Creation date: 07-17-2014
 * 
 * XDoclet definition:
 * @struts.action parameter="type" validate="true"
 */
public class DelegatingActionProxy extends DispatchAction {
	     private Variable vari;
         private Service service0;
	

	public Service getService0() {
			return service0;
		}

		public void setService0(Service service0) {
			this.service0 = service0;
		}

	//	public ActionForward execute(ActionMapping mapping, ActionForm form,
//			HttpServletRequest request, HttpServletResponse response)
//			throws Exception {
//		RegisterForm registerForm=(RegisterForm) form;
//		userService0.register(registerForm.getEmail(),registerForm.getPass(),registerForm.getName(),registerForm.getTelphone());
//	//	request.getSession().setAttribute("username", registerForm.getUsername());
//		return mapping.findForward("success");
//	}
	//µÇÂ½
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		RegisterForm registerform=(RegisterForm) form;
	//	User u=userService0.login(registerForm.getEmail(), registerForm.getPass());
	//	request.getSession().setAttribute("username", registerForm.getUsername());
		//if(u!=null)
//		return mapping.findForward("success");
//		else
	//	System.out.println(registerform.getEmail());
		System.out.println(AopUtils.isAopProxy(service0));
		System.out.println(AopUtils.isCglibProxy(service0));
		System.out.println(AopUtils.isJdkDynamicProxy(service0));
		
		List<User> list=service0.getUser(registerform.getEmail(),registerform.getPass());
		if(list!=null&&list.size()==1)
			return mapping.findForward("success");
		else
		return mapping.findForward("error");
	}
	//×¢²á
	
	public ActionForward register(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response)
			throws Exception {
		RegisterForm registerform=(RegisterForm) form;
		System.out.println("username="+registerform.getEmail());
		if(!vari.map_users.containsKey(registerform.getEmail())){
		if(service0.saveUser(registerform.getEmail(),registerform.getPass(),registerform.getName(),registerform.getTelphone())){
//		userService0.register(registerForm.getEmail(),registerForm.getPass(),registerForm.getName(),registerForm.getTelphone());
	//	request.getSession().setAttribute("username", registerForm.getUsername());
			vari.map_users.put(registerform.getEmail(),new User(registerform.getEmail(),registerform.getPass()));
		return mapping.findForward("success");}
		else return mapping.findForward("error");
		}
		else{
			request.setAttribute("info", URLEncoder.encode("×¢²áÊ§°Ü¡£¡£¡£","utf-8"));
			return mapping.findForward("info");}
		
	}
}