/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.easyop.action;

import java.io.IOException;
import java.util.ArrayList;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.springframework.aop.support.AopUtils;

import com.easyop.dbconn.Dbcon;
import com.easyop.service.EditorSer;
import com.easyop.service.InEditorSer;

/** 
 * MyEclipse Struts
 * Creation date: 07-22-2014
 * 
 * XDoclet definition:
 * @struts.action path="/Editor" name="modeltable" parameter="type" validate="true"
 */
public class Dispatchaction extends DispatchAction {
	Logger log=Logger.getLogger("logfile");
	private EditorSer editorSer;



	public EditorSer getEditorSer() {
		return editorSer;
	}



	public void setEditorSer(EditorSer editorSer) {
		this.editorSer = editorSer;
	}



	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward visit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
         String table="tnews";
         Dbcon db=new Dbcon();
         //获取修改表列名
         int[] exout=new int[]{9,10};
		request.getSession().setAttribute("titles", db.getTabTitles(table,exout));
		//hibernate获取表数据
		System.out.println("editorser="+editorSer);
		request.getSession().setAttribute("datalist",editorSer.getDataList());

        try {
			request.getRequestDispatcher("/crud.jsp").forward(request, response);
		} catch (ServletException e) {
			
			log.error("error:"+e);
		} catch (IOException e) {
			
			log.error("error:"+e);
		}
		return null;
	}
}