<?php
echo "把数据压缩后写入文件演示 >> gzwrite()";echo"<br>";
$id = gzopen("test.gz","w");
gzwrite($id,"Hello world!\n");
gzwrite($id,"1234567890\n",5);
gzclose($id);
echo "读压缩文件中解压缩后的字符演示 >> gzgetc()";echo"<br>";
$id = gzopen("test.gz","w");
gzputs($id,"This is a test.");
gzclose($id);
$id = gzopen("test.gz","r");
$temp = gzgetc($id);
echo $temp."";
$temp = gzgetc($id);
echo $temp."<br>";
gzclose($id);
echo "读压缩文件中解压缩后的字符串演示>>gzgets()";echo"<br>";
$id = gzopen("test.gz","w");
gzputs($id,"This is a test.\n");
gzputs($id,"The second line.\n");
gzclose($id);
$id = gzopen("test.gz","r");
$temp = gzgets($id,256);
echo $temp."<br>";
$temp = gzgets($id,10);
echo $temp."<br>";
gzclose($id);
echo "读压缩文件中解压缩后的字符串 >> gzgetss()";echo"<br>";
$id = gzopen("test.gz","w");
gzputs($id,"<html><title>this is a test.</title>\n");
gzputs($id,"</html>the second line.\n");
gzclose($id);
$id = gzopen("test.gz","r");
$temp = gzgetss($id,256);
echo $temp."<br>";
$temp=gzgetss($id,10);
echo$temp."<br>";
gzclose($id);
echo"从压缩文件读出解压缩后指定长度字符串演示 >> gzread()";echo"<br>";
$id=gzopen("test.gz","w");
gzputs($id,"Oh,welcome to PHP world!\n");
gzputs($id,"this's a phpbook.\n");
gzclose($id);
$id=gzopen("test.gz","r");
$temp=gzread($id,256);
echo$temp."<br>";
gzclose($id);
echo"解压缩指针后的全部数据并在标准输出中显示出来演示 >> gzpassthru()";echo"<br>";
$id=gzopen("test.gz","w");
gzputs($id,"Hi!rainlion is my old friend!\n");
gzclose($id);
$id=gzopen("test.gz","r");
echo gzgets($id,3)."<br>";
gzpassthru($id);
?>